const fs = require('fs')
const path = require('path')
const fetch = require('node-fetch')
const sharp = require('sharp')

const manifest = require('./image-manifest.json')

const outBase = path.resolve(__dirname, '..', 'public', 'assets', 'products')
const widths = [360, 640, 960, 1280, 1600]

async function download(url){
  const res = await fetch(url)
  if(!res.ok) throw new Error(`Failed to download ${url}: ${res.status}`)
  return Buffer.from(await res.arrayBuffer())
}

async function ensureDir(dir){
  await fs.promises.mkdir(dir, {recursive:true})
}

async function run(){
  for(const [id, entries] of Object.entries(manifest)){
    const dir = path.join(outBase, id)
    await ensureDir(dir)

    for(let i=0;i<entries.length;i++){
      const entry = entries[i]
      const lightUrl = typeof entry === 'string' ? entry : entry.light
      const darkUrl = typeof entry === 'object' && entry.dark ? entry.dark : null

      console.log(`Processing ${id} image ${i}`)

      let lightBuf
      try{
        lightBuf = await download(lightUrl)
      }catch(err){
        console.error(`Skipping ${id}/${i}: download failed: ${err.message}`)
        continue
      }

      try{
        const origPath = path.join(dir, `${i}-orig.jpg`)
        await sharp(lightBuf).jpeg({quality:80}).toFile(origPath)

        for(const w of widths){
          const avifPath = path.join(dir, `${i}-${w}.avif`)
          const webpPath = path.join(dir, `${i}-${w}.webp`)
          const jpgPath = path.join(dir, `${i}-${w}.jpg`)

          await sharp(lightBuf).resize(w).avif({quality:80}).toFile(avifPath)
          await sharp(lightBuf).resize(w).webp({quality:80}).toFile(webpPath)
          await sharp(lightBuf).resize(w).jpeg({quality:80}).toFile(jpgPath)
          console.log(`Wrote ${id}/${i} @ ${w}px`)
        }
      }catch(err){
        console.error(`Failed processing ${id}/${i}: ${err.message}`)
      }

      // Dark variants: either from darkUrl or generated by darkening the light image
      let darkBuf = null
      if(darkUrl){
        try{ darkBuf = await download(darkUrl) }catch(err){ console.error(`Failed download dark ${id}/${i}: ${err.message}`) }
      }

      if(!darkBuf){
        // generate darkBuf by modulating brightness/saturation from lightBuf
        try{
          darkBuf = await sharp(lightBuf).jpeg().toBuffer()
        }catch(err){ darkBuf = null }
      }

      if(darkBuf){
        try{
          for(const w of widths){
            const avifPath = path.join(dir, `${i}-dark-${w}.avif`)
            const webpPath = path.join(dir, `${i}-dark-${w}.webp`)
            const jpgPath = path.join(dir, `${i}-dark-${w}.jpg`)

            // apply a subtle darken/tint
            await sharp(darkBuf).resize(w).modulate({brightness:0.75, saturation:0.95}).avif({quality:80}).toFile(avifPath)
            await sharp(darkBuf).resize(w).modulate({brightness:0.75, saturation:0.95}).webp({quality:80}).toFile(webpPath)
            await sharp(darkBuf).resize(w).modulate({brightness:0.75, saturation:0.95}).jpeg({quality:80}).toFile(jpgPath)
            console.log(`Wrote ${id}/${i}-dark @ ${w}px`)
          }
        }catch(err){
          console.error(`Failed writing dark variants ${id}/${i}: ${err.message}`)
        }
      }
    }
  }
}

run().then(()=> console.log('Done')).catch(err=>{
  console.error(err)
  process.exit(1)
})
